# coding: utf-8

"""
FastAPI

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from whiskerrag_client.api.retrieval_api import RetrievalApi


class TestRetrievalApi(unittest.TestCase):
    """RetrievalApi unit test stubs"""

    def setUp(self) -> None:
        self.api = RetrievalApi()

    def tearDown(self) -> None:
        pass

    def test_retrieve_knowledge_content_api_retrieval_knowledge_post(self) -> None:
        """Test case for retrieve_knowledge_content_api_retrieval_knowledge_post

        Retrieve Knowledge Content
        """
        pass

    def test_retrieve_space_content_api_retrieval_space_post(self) -> None:
        """Test case for retrieve_space_content_api_retrieval_space_post

        Retrieve Space Content
        """
        pass


if __name__ == "__main__":
    unittest.main()
