# coding: utf-8

"""
FastAPI

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from whiskerrag_client.models.response_model_page_response_chunk import (
    ResponseModelPageResponseChunk,
)


class TestResponseModelPageResponseChunk(unittest.TestCase):
    """ResponseModelPageResponseChunk unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ResponseModelPageResponseChunk:
        """Test ResponseModelPageResponseChunk
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `ResponseModelPageResponseChunk`
        """
        model = ResponseModelPageResponseChunk()
        if include_optional:
            return ResponseModelPageResponseChunk(
                success = True,
                data = whiskerrag_client.models.page_response[chunk].PageResponse[Chunk](
                    items = [
                        whiskerrag_client.models.chunk.Chunk(
                            chunk_id = '',
                            embedding = [
                                1.337
                                ],
                            context = '',
                            knowledge_id = '',
                            embedding_model_name = '',
                            space_id = '',
                            metadata = whiskerrag_client.models.metadata.metadata(),
                            created_at = '',
                            updated_at = '', )
                        ],
                    total = 56,
                    page = 56,
                    page_size = 56,
                    total_pages = 56, ),
                message = ''
            )
        else:
            return ResponseModelPageResponseChunk(
                success = True,
        )
        """

    def testResponseModelPageResponseChunk(self):
        """Test ResponseModelPageResponseChunk"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
