# coding: utf-8

"""
FastAPI

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from whiskerrag_client.models.retrieval_chunk import RetrievalChunk


class TestRetrievalChunk(unittest.TestCase):
    """RetrievalChunk unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RetrievalChunk:
        """Test RetrievalChunk
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `RetrievalChunk`
        """
        model = RetrievalChunk()
        if include_optional:
            return RetrievalChunk(
                chunk_id = '',
                embedding = [
                    1.337
                    ],
                context = '',
                knowledge_id = '',
                embedding_model_name = '',
                space_id = '',
                metadata = whiskerrag_client.models.metadata.metadata(),
                created_at = '',
                updated_at = '',
                similarity = 1.337
            )
        else:
            return RetrievalChunk(
                context = '',
                knowledge_id = '',
                space_id = '',
                similarity = 1.337,
        )
        """

    def testRetrievalChunk(self):
        """Test RetrievalChunk"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
