# coding: utf-8

"""
FastAPI

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from whiskerrag_client.models.knowledge_split_config import KnowledgeSplitConfig


class TestKnowledgeSplitConfig(unittest.TestCase):
    """KnowledgeSplitConfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> KnowledgeSplitConfig:
        """Test KnowledgeSplitConfig
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `KnowledgeSplitConfig`
        """
        model = KnowledgeSplitConfig()
        if include_optional:
            return KnowledgeSplitConfig(
                separators = [
                    ''
                    ],
                split_regex = '',
                chunk_size = 1.0,
                chunk_overlap = 0.0
            )
        else:
            return KnowledgeSplitConfig(
        )
        """

    def testKnowledgeSplitConfig(self):
        """Test KnowledgeSplitConfig"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
