# coding: utf-8

"""
FastAPI

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from whiskerrag_client.models.retrieval_by_knowledge_request import (
    RetrievalByKnowledgeRequest,
)


class TestRetrievalByKnowledgeRequest(unittest.TestCase):
    """RetrievalByKnowledgeRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RetrievalByKnowledgeRequest:
        """Test RetrievalByKnowledgeRequest
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `RetrievalByKnowledgeRequest`
        """
        model = RetrievalByKnowledgeRequest()
        if include_optional:
            return RetrievalByKnowledgeRequest(
                question = '',
                embedding_model_name = 'openai',
                similarity_threshold = 0.0,
                top = 1.0,
                metadata_filter = whiskerrag_client.models.metadata_filter.Metadata Filter(),
                knowledge_id_list = [
                    ''
                    ]
            )
        else:
            return RetrievalByKnowledgeRequest(
                question = '',
                embedding_model_name = 'openai',
                knowledge_id_list = [
                    ''
                    ],
        )
        """

    def testRetrievalByKnowledgeRequest(self):
        """Test RetrievalByKnowledgeRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
