# coding: utf-8

"""
FastAPI

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from whiskerrag_client.models.page_response_retrieval_chunk import (
    PageResponseRetrievalChunk,
)


class TestPageResponseRetrievalChunk(unittest.TestCase):
    """PageResponseRetrievalChunk unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PageResponseRetrievalChunk:
        """Test PageResponseRetrievalChunk
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `PageResponseRetrievalChunk`
        """
        model = PageResponseRetrievalChunk()
        if include_optional:
            return PageResponseRetrievalChunk(
                items = [
                    whiskerrag_client.models.retrieval_chunk.RetrievalChunk(
                        chunk_id = '', 
                        embedding = [
                            1.337
                            ], 
                        context = '', 
                        knowledge_id = '', 
                        embedding_model_name = '', 
                        space_id = '', 
                        metadata = whiskerrag_client.models.metadata.metadata(), 
                        created_at = '', 
                        updated_at = '', 
                        similarity = 1.337, )
                    ],
                total = 56,
                page = 56,
                page_size = 56,
                total_pages = 56
            )
        else:
            return PageResponseRetrievalChunk(
                items = [
                    whiskerrag_client.models.retrieval_chunk.RetrievalChunk(
                        chunk_id = '', 
                        embedding = [
                            1.337
                            ], 
                        context = '', 
                        knowledge_id = '', 
                        embedding_model_name = '', 
                        space_id = '', 
                        metadata = whiskerrag_client.models.metadata.metadata(), 
                        created_at = '', 
                        updated_at = '', 
                        similarity = 1.337, )
                    ],
                total = 56,
                page = 56,
                page_size = 56,
                total_pages = 56,
        )
        """

    def testPageResponseRetrievalChunk(self):
        """Test PageResponseRetrievalChunk"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
