# coding: utf-8

"""
FastAPI

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from whiskerrag_client.api.task_api import TaskApi


class TestTaskApi(unittest.TestCase):
    """TaskApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TaskApi()

    def tearDown(self) -> None:
        pass

    def test_get_task_list_api_task_detail_get(self) -> None:
        """Test case for get_task_list_api_task_detail_get

        Get Task List
        """
        pass

    def test_get_task_list_api_task_list_post(self) -> None:
        """Test case for get_task_list_api_task_list_post

        Get Task List
        """
        pass


if __name__ == "__main__":
    unittest.main()
