# coding: utf-8

"""
FastAPI

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from whiskerrag_client.models.chunk import Chunk


class TestChunk(unittest.TestCase):
    """Chunk unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Chunk:
        """Test Chunk
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `Chunk`
        """
        model = Chunk()
        if include_optional:
            return Chunk(
                chunk_id = '',
                embedding = [
                    1.337
                    ],
                context = '',
                knowledge_id = '',
                embedding_model_name = '',
                space_id = '',
                metadata = None,
                created_at = '',
                updated_at = ''
            )
        else:
            return Chunk(
                context = '',
                knowledge_id = '',
                space_id = '',
        )
        """

    def testChunk(self):
        """Test Chunk"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
