# coding: utf-8

"""
FastAPI

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from whiskerrag_client.models.embedding_model_enum import EmbeddingModelEnum


class TestEmbeddingModelEnum(unittest.TestCase):
    """EmbeddingModelEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEmbeddingModelEnum(self):
        """Test EmbeddingModelEnum"""
        # inst = EmbeddingModelEnum()


if __name__ == "__main__":
    unittest.main()
