# coding: utf-8

"""
FastAPI

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from whiskerrag_client.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_health_checker_api_health_checker_get(self) -> None:
        """Test case for health_checker_api_health_checker_get

        Health Checker
        """
        pass

    def test_home_page_get(self) -> None:
        """Test case for home_page_get

        Home Page
        """
        pass


if __name__ == "__main__":
    unittest.main()
