# coding: utf-8

"""
FastAPI

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.1.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from whiskerrag_client.api.chunk_api import ChunkApi


class TestChunkApi(unittest.TestCase):
    """ChunkApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ChunkApi()

    def tearDown(self) -> None:
        pass

    def test_get_chunk_list_api_chunk_list_post(self) -> None:
        """Test case for get_chunk_list_api_chunk_list_post

        Get Chunk List
        """
        pass


if __name__ == "__main__":
    unittest.main()
