repos:
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        exclude: '^\.cursor/.*'

- repo: local
  hooks:
    - id: lint
      name: lint
      entry: poetry run lint
      language: system
      pass_filenames: false
      always_run: true
      verbose: true

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
        exclude: '^\.cursor/.*'
    -   id: end-of-file-fixer
        exclude: '^\.cursor/.*'
    -   id: check-yaml
        exclude: '^\.cursor/.*'
    -   id: check-added-large-files
        exclude: '^\.cursor/.*'
    -   id: check-toml
        exclude: '^\.cursor/.*'
    -   id: check-merge-conflict
        exclude: '^\.cursor/.*'
